name: DanVPS WebHost - Github Edition - Setup

on:
  workflow_dispatch:

jobs:
  build:
    name: Initializing DanVPS WebHost Setup
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Preparing VPS...
        run: Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ehtixee7tplci32xr8wai/temppreparation.txt?rlkey=uxuk9pgj1syt2sgbc3d2p4ghg&dl=1" -OutFile "Preparation.bat"

      - name: Installing Admin/Control Panel and stuff..
        run: cmd /c Preparation.bat

      - name: Configuring NGROK for the domain...
        run: | 
             C:\ngrok\ngrok.exe config add-authtoken $Env:WhatAreYaLookingHere
             py C:\ngrok.py
        env:
             WhatAreYaLookingHere: ${{ secrets.NGROKAUTH }}

      - name: Server Is Ready!
        run: cmd /c C:\finalize.bat
